version: '3.5'

services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  node-exporter:
    image: prom/node-exporter
    restart: always
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
    ports:
      - 9100:9100
    depends_on:
      - prometheus
  mysql:
    image: mysql:5
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prometheus
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  mysql-exporter:
    image: prom/mysqld-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: root:password@(mysql:3306)/prometheus
    ports:
      - 9104:9104
    depends_on:
      - mysql
  web-server:
    build:
      context: .
      dockerfile: go/Dockerfile
    restart: always
    ports:
      - 1323:1323
    depends_on:
      - prometheus
      - mysql