global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']
  - job_name: 'webserver-exporter'
    static_configs:
      - targets: ['web-server:1323']
