{
 "title": "Custom metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Instance #",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(process_start_time_seconds{job='webserver-exporter'})"
    }
   ]
  },
  {
   "title": "Max goroutine",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(go_goroutines{job='webserver-exporter'})"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, avg by (api) (api_durations_msec{quantile=\"0.5\"})))"
    }
   ]
  },
  {
   "title": "Request #",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (api) (rate(api_durations_msec_count[$interval])*100))"
    }
   ]
  },
  {
   "title": "Most Time Consuming",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, avg by (api) (api_durations_msec{quantile='0.5'}) * sum by (api) (api_durations_msec_count))) / 1000"
    }
   ]
  }
 ]
}